version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpfoyer
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-foyer:
    image: lina222/tp-foyer-5.0.0
    container_name: app-foyer
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url": "jdbc:mysql://mysqldb:3306/tpfoyer?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
             "spring.datasource.username": "root",
             "spring.datasource.password": "root",
             "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
             "spring.jpa.hibernate.ddl-auto": "update"
           }'

volumes:
  db_data:
